project:
  type: website

website:
  title: "Data Storytelling"
  navbar:
    right:
      - text: "About Me"
        file: about.qmd
      - icon: github
        href: https://github.com/NutchanokS

format:
  html:
    theme: yeti
    css: styles.css



