project:
  type: website

website:
  title: "Data Storytelling: Freshwater Nitrate Monitoring"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NutchanokS
format:
  html:
    theme: materia
    css: styles.css



